#!/bin/bash

# Xeno - Pre-Deployment Checklist Script
# Run this before deploying to Render

echo "🚀 Xeno Deployment Preparation"
echo "=============================="
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ] || [ ! -d "frontend" ]; then
    echo "❌ Error: Run this script from the xeno project root directory"
    exit 1
fi

echo "✓ Running from project root"
echo ""

# Check Git status
echo "📋 Checking Git status..."
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "❌ Not a git repository. Run: git init"
    exit 1
fi

echo "✓ Git initialized"

# Check for uncommitted changes
if ! git diff-index --quiet HEAD -- 2>/dev/null; then
    echo "⚠️  Warning: You have uncommitted changes"
    echo "   Run: git add . && git commit -m 'Ready for deployment'"
else
    echo "✓ No uncommitted changes"
fi

# Check if remote is set
if ! git remote get-url origin > /dev/null 2>&1; then
    echo "❌ No git remote 'origin' set"
    echo "   1. Create a repo on GitHub"
    echo "   2. Run: git remote add origin https://github.com/YOUR_USERNAME/xeno.git"
    exit 1
fi

echo "✓ Git remote configured: $(git remote get-url origin)"
echo ""

# Check for required files
echo "📋 Checking required files..."

required_files=(
    "package.json"
    "prisma/schema.prisma"
    "render.yaml"
    "Dockerfile"
    "frontend/package.json"
    "frontend/Dockerfile"
    "src/server.js"
)

missing_files=0
for file in "${required_files[@]}"; do
    if [ ! -f "$file" ]; then
        echo "❌ Missing: $file"
        missing_files=$((missing_files + 1))
    else
        echo "✓ $file"
    fi
done

if [ $missing_files -gt 0 ]; then
    echo ""
    echo "❌ Missing $missing_files required file(s)"
    exit 1
fi

echo ""
echo "📋 Checking environment variables..."

# Check .env file
if [ ! -f ".env" ]; then
    echo "⚠️  Warning: No .env file found (okay for production, but needed for local testing)"
else
    echo "✓ .env file exists"
    
    # Check for critical env vars in .env
    if grep -q "JWT_SECRET" .env; then
        echo "✓ JWT_SECRET found in .env"
    else
        echo "⚠️  JWT_SECRET not in .env (will be generated by Render)"
    fi
    
    if grep -q "DEV_SHOP_ADMIN_ACCESS_TOKEN" .env; then
        echo "✓ Shopify token found in .env"
    else
        echo "⚠️  No Shopify token in .env"
    fi
fi

echo ""
echo "📋 Checking dependencies..."

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo "⚠️  node_modules not found. Installing..."
    npm install
else
    echo "✓ Backend dependencies installed"
fi

if [ ! -d "frontend/node_modules" ]; then
    echo "⚠️  Frontend node_modules not found. Installing..."
    cd frontend && npm install && cd ..
else
    echo "✓ Frontend dependencies installed"
fi

echo ""
echo "📋 Testing Prisma..."

# Generate Prisma client
if npx prisma generate > /dev/null 2>&1; then
    echo "✓ Prisma client generated successfully"
else
    echo "❌ Prisma generate failed"
    exit 1
fi

echo ""
echo "📋 Checking .gitignore..."

if [ ! -f ".gitignore" ]; then
    echo "⚠️  No .gitignore found. Creating one..."
    cat > .gitignore << EOF
node_modules
.env
.env.local
dist
build
*.log
.DS_Store
.vscode
.idea
EOF
    echo "✓ Created .gitignore"
else
    echo "✓ .gitignore exists"
fi

echo ""
echo "=============================="
echo "✅ Pre-deployment checks complete!"
echo ""
echo "📝 Next Steps:"
echo ""
echo "1. Push to GitHub:"
echo "   git add ."
echo "   git commit -m 'Ready for Render deployment'"
echo "   git push origin main"
echo ""
echo "2. Deploy on Render:"
echo "   • Go to https://dashboard.render.com"
echo "   • Click 'New +' → 'Blueprint'"
echo "   • Connect your GitHub repo"
echo "   • Set environment variables:"
echo "     - JWT_SECRET (click 'Generate')"
echo "     - DEV_SHOP_DOMAIN: vivekxenostore.myshopify.com"
echo "     - DEV_SHOP_ADMIN_ACCESS_TOKEN: (your Shopify token)"
echo "   • Click 'Apply'"
echo ""
echo "3. Monitor deployment:"
echo "   • Watch logs for both backend and frontend"
echo "   • Backend should start on port 5001"
echo "   • Frontend should build and serve static files"
echo ""
echo "4. Test deployment:"
echo "   • Backend: https://xeno-backend.onrender.com/health"
echo "   • Frontend: https://xeno-frontend.onrender.com"
echo "   • API Docs: https://xeno-backend.onrender.com/docs"
echo ""
echo "📖 Full guide: See RENDER_DEPLOYMENT.md"
echo ""
